#!/bin/sh
# Usage: script/cibuild
# CI build script
#
set -e

export PATH="/usr/share/rbenv/shims:$PATH"
export RACK_ROOT=$(cd "$(dirname $0)"/.. && pwd)
export RACK_ENV="test"
export RAILS_ENV="test"
export RBENV_VERSION="2.0.0-p353"

# clean out the ruby environment
export RUBYLIB=
export RUBYOPT=

# bootstrap gem environment changes
cd "$RACK_ROOT"
echo 'Bootstrapping gems...'
script/bootstrap

echo "==> Running tests…"

bundle exec rake
